### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by sukeyisme** [madmongo1/blog-new-year-2021#2]
connection_cache.cpp:44:37: error: no match for 'operator!=' (operand types are 'const executor_type' {aka 'const boost::asio::io_context::basic_executor_type<std::allocator<void>, 0>'} and 'boost::asio::any_io_executor')
   44 |     co_return impl_->get_executor() != my_executor
      |               ~~~~~~~~~~~~~~~~~~~~~ ^~ ~~~~~~~~~~~
      |                                  |     |
      |                                  |     boost::asio::any_io_executor
      |                                  const executor_type {aka const boost::asio::io_context::basic_executor_type<std::allocator<void>, 0>}

**Comment by madmongo1** [comment]
hmm.

Which compiler is this?

**Comment by sukeyisme** [comment]
gcc version 10.2.1 20210110 (Debian 10.2.1-6)

**Comment by sukeyisme** [comment]
downgrade to boost 1.75 compile successed.
