### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by sukeyisme** [madmongo1/blog-new-year-2021#3]
When enable MUTLI_THREADED.

/usr/include/c++/10/bits/unique_ptr.h:962:30: error: no matching function for call to 'http::connection_cache_impl::connection_cache_impl(boost::asio::io_context::basic_executor_type<std::allocator<void>, 0>, boost::asio::ssl::context&, http::connect_options)'
  962 |     { return unique_ptr<_Tp>(new _Tp(std::forward<_Args>(__args)...)); }

**Comment by madmongo1** [comment]
Fixed. Thank you.
