### ISSUE TITLE
How to write a function to sync get return value?

### ISSUE THREAD

**Issue by sukeyisme** [madmongo1/blog-new-year-2021#6]

**Comment by madmongo1** [comment]
I need more information to be able to answer your question.
Get a return value from what?

**Comment by sukeyisme** [comment]
net::co_spawn(
        ioctx.get_executor(), [] { return crawl(); }, net::detached);

This is a async call,If want to get return value sync how to do?

**Comment by madmongo1** [comment]
the `net::detached` completion token is causing the return value to be deliberately discarded. You can get the return value type replacing `detached` with your own lambda or another completion token such as `use_awaitable` or `use_future`

So here's one way:

```
auto f = net::co_spawn(ioctx.get_executor(), crawl(), asio::use_future);
// f is a std::future
f.get();  // block until the future has a value or error
```

However, you will want to do this on a different thread to the thread that calls `run` on the `io_context`

**Comment by sukeyisme** [comment]
Yes,will have any problem?

**Comment by sukeyisme** [comment]
how to replacing detached with your own lambda？

Richard Hodges ***@***.***> 于 2021年11月18日周四 17:51写道：
